name: my-workflow #optional
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'wrong-docs/**'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps: #all steps of check-bats-version
      - uses: actions/checkout@v2 # STEP 1, there is a "checkout" repo in github.com/actions
      - uses: actions/setup-node@v2 # STEP 2
        with:
          node-version: '14'
      #- uses: actions/hello-world-action/action-one.yml@v1
      - run: npm install -g bats # STEP 3: using npm to download the bats package
      - run: bats -v # STEP 4
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: emref/ci-test #copied from Docker
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

